/**
 * ML Service — fires AQI24
 * ========================
 * Loads the trained XGBoost/LightGBM model predictions from the static JSON
 * generated by backend/ml/train.py using the real NASA FIRMS VIIRS dataset.
 *
 * When your team's backend API is ready, replace fetchMLPredictions() below
 * with a real API call — all pages keep working unchanged.
 */

let _cache = null;

export async function fetchMLPredictions() {
  if (_cache) return _cache;
  try {
    const res = await fetch('/ml/predictions.json');
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    _cache = await res.json();
    return _cache;
  } catch (err) {
    return { error: err.message };
  }
}

export async function fetchModelMeta() {
  try {
    const res = await fetch('/ml/model_meta.json');
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } catch (err) {
    return { error: err.message };
  }
}

/**
 * Get regional predictions for a specific season.
 * @param {string} season - 'winter' | 'summer' | 'post_monsoon' | 'monsoon'
 * @param {string} brightnessLevel - 'low' | 'medium' | 'high' | 'extreme'
 */
export async function getRegionalPredictions(season = null, brightnessLevel = 'medium') {
  const data = await fetchMLPredictions();
  if (data.error) return { error: data.error, predictions: [] };

  let predictions = data.regional_predictions || [];
  if (season) predictions = predictions.filter(p => p.season === season);
  predictions = predictions.filter(p => p.brightness_level === brightnessLevel);

  return { predictions, model_info: data.model_info };
}

/**
 * Get severity color for a class (0-3).
 */
export function severityColor(sev) {
  return ['#34d399', '#fbbf24', '#fb923c', '#f43f5e'][sev] ?? '#64748b';
}

/**
 * Get severity background for a class.
 */
export function severityBg(sev) {
  return [
    'rgba(52,211,153,0.1)',
    'rgba(251,191,36,0.1)',
    'rgba(251,146,60,0.1)',
    'rgba(244,63,94,0.1)',
  ][sev] ?? 'rgba(100,116,139,0.1)';
}
